// Kuratierte Lebensmittelliste: deutscher Name → USDA-Eintrag (SR Legacy, exakte Beschreibung)
// oder eigene Richtwerte (`eigen`, je 100 g, EU-Kohlenhydrate ohne Ballaststoffe).
// Neue Lebensmittel hier eintragen und `node tools/build-lebensmittel.js` ausführen.
// stueckG: typisches Gewicht eines Stücks (essbarer Anteil), optional.
// kcalAusMakros: kcal nach EU-Faktoren neu berechnen (4/4/9, Ballaststoffe 2), wenn USDA abweicht.

const obst = 'obst';
const gemuese = 'gemuese';
const getreide = 'getreide';
const huelsen = 'huelsenfruechte';
const milch = 'milch_ei';
const fleisch = 'fleisch_fisch';
const nuesse = 'nuesse_samen';
const fette = 'oele_fette';
const suess = 'suesses';
const getraenke = 'getraenke';
const sonstiges = 'sonstiges';

export const LISTE = [
  // Obst
  { id: 'apfel', name: 'Apfel', kategorie: obst, usda: 'Apples, raw, with skin', stueckG: 170 },
  { id: 'banane', name: 'Banane', kategorie: obst, usda: 'Bananas, raw', stueckG: 120 },
  { id: 'birne', name: 'Birne', kategorie: obst, usda: 'Pears, raw', stueckG: 170 },
  { id: 'orange', name: 'Orange', kategorie: obst, usda: 'Oranges, raw, all commercial varieties', stueckG: 150 },
  { id: 'mandarine', name: 'Mandarine/Clementine', kategorie: obst, usda: 'Tangerines, (mandarin oranges), raw', stueckG: 75 },
  { id: 'kiwi', name: 'Kiwi', kategorie: obst, usda: 'Kiwifruit, green, raw', stueckG: 75 },
  { id: 'kiwi_gold', name: 'Kiwi Gold', kategorie: obst, usda: 'Kiwifruit, ZESPRI SunGold, raw', stueckG: 85 },
  { id: 'erdbeeren', name: 'Erdbeeren', kategorie: obst, usda: 'Strawberries, raw' },
  { id: 'heidelbeeren', name: 'Heidelbeeren', kategorie: obst, usda: 'Blueberries, raw' },
  { id: 'himbeeren', name: 'Himbeeren', kategorie: obst, usda: 'Raspberries, raw' },
  { id: 'brombeeren', name: 'Brombeeren', kategorie: obst, usda: 'Blackberries, raw' },
  { id: 'johannisbeeren', name: 'Johannisbeeren (rot)', kategorie: obst, usda: 'Currants, red and white, raw' },
  { id: 'weintrauben', name: 'Weintrauben', kategorie: obst, usda: 'Grapes, red or green (European type, such as Thompson seedless), raw' },
  { id: 'ananas', name: 'Ananas', kategorie: obst, usda: 'Pineapple, raw, all varieties' },
  { id: 'mango', name: 'Mango', kategorie: obst, usda: 'Mangos, raw', stueckG: 300 },
  { id: 'papaya', name: 'Papaya', kategorie: obst, usda: 'Papayas, raw' },
  { id: 'wassermelone', name: 'Wassermelone', kategorie: obst, usda: 'Watermelon, raw' },
  { id: 'honigmelone', name: 'Honigmelone', kategorie: obst, usda: 'Melons, honeydew, raw' },
  { id: 'pfirsich', name: 'Pfirsich', kategorie: obst, usda: 'Peaches, yellow, raw', stueckG: 150 },
  { id: 'nektarine', name: 'Nektarine', kategorie: obst, usda: 'Nectarines, raw', stueckG: 140 },
  { id: 'pflaume', name: 'Pflaume/Zwetschge', kategorie: obst, usda: 'Plums, raw', stueckG: 40 },
  { id: 'aprikose', name: 'Aprikose', kategorie: obst, usda: 'Apricots, raw', stueckG: 35 },
  { id: 'kirschen', name: 'Kirschen (süß)', kategorie: obst, usda: 'Cherries, sweet, raw' },
  { id: 'sauerkirschen', name: 'Sauerkirschen', kategorie: obst, usda: 'Cherries, sour, red, raw' },
  { id: 'grapefruit', name: 'Grapefruit', kategorie: obst, usda: 'Grapefruit, raw, pink and red, all areas', stueckG: 250 },
  { id: 'zitrone', name: 'Zitrone', kategorie: obst, usda: 'Lemons, raw, without peel', stueckG: 60 },
  { id: 'granatapfel', name: 'Granatapfel', kategorie: obst, usda: 'Pomegranates, raw' },
  { id: 'kaki', name: 'Kaki', kategorie: obst, usda: 'Persimmons, japanese, raw', stueckG: 170 },
  { id: 'datteln', name: 'Datteln (Medjool)', kategorie: obst, usda: 'Dates, medjool', stueckG: 24 },
  { id: 'rosinen', name: 'Rosinen/Sultaninen', kategorie: obst, usda: 'Raisins, dark, seedless' },
  { id: 'feigen_getrocknet', name: 'Feigen, getrocknet', kategorie: obst, usda: 'Figs, dried, uncooked' },
  { id: 'aprikosen_getrocknet', name: 'Aprikosen, getrocknet', kategorie: obst, usda: 'Apricots, dried, sulfured, uncooked' },
  { id: 'cranberries_getrocknet', name: 'Cranberries, getrocknet', kategorie: obst, usda: 'Cranberries, dried, sweetened' },

  // Gemüse
  { id: 'brokkoli', name: 'Brokkoli', kategorie: gemuese, usda: 'Broccoli, raw' },
  { id: 'blumenkohl', name: 'Blumenkohl', kategorie: gemuese, usda: 'Cauliflower, raw' },
  { id: 'karotte', name: 'Karotte/Möhre', kategorie: gemuese, usda: 'Carrots, raw', stueckG: 70 },
  { id: 'paprika_rot', name: 'Paprika, rot', kategorie: gemuese, usda: 'Peppers, sweet, red, raw', stueckG: 160 },
  { id: 'paprika_gelb', name: 'Paprika, gelb', kategorie: gemuese, usda: 'Peppers, sweet, yellow, raw', stueckG: 160 },
  { id: 'paprika_gruen', name: 'Paprika, grün', kategorie: gemuese, usda: 'Peppers, sweet, green, raw', stueckG: 160 },
  { id: 'tomate', name: 'Tomate', kategorie: gemuese, usda: 'Tomatoes, red, ripe, raw, year round average', stueckG: 120 },
  { id: 'gurke', name: 'Gurke', kategorie: gemuese, usda: 'Cucumber, with peel, raw', stueckG: 400 },
  { id: 'zucchini', name: 'Zucchini', kategorie: gemuese, usda: 'Squash, summer, zucchini, includes skin, raw', stueckG: 250 },
  { id: 'aubergine', name: 'Aubergine', kategorie: gemuese, usda: 'Eggplant, raw', stueckG: 300 },
  { id: 'spinat', name: 'Spinat', kategorie: gemuese, usda: 'Spinach, raw' },
  { id: 'gruenkohl', name: 'Grünkohl', kategorie: gemuese, usda: 'Kale, raw' },
  { id: 'rosenkohl', name: 'Rosenkohl', kategorie: gemuese, usda: 'Brussels sprouts, raw' },
  { id: 'weisskohl', name: 'Weißkohl', kategorie: gemuese, usda: 'Cabbage, raw' },
  { id: 'rotkohl', name: 'Rotkohl', kategorie: gemuese, usda: 'Cabbage, red, raw' },
  { id: 'wirsing', name: 'Wirsing', kategorie: gemuese, usda: 'Cabbage, savoy, raw' },
  { id: 'chinakohl', name: 'Chinakohl', kategorie: gemuese, usda: 'Cabbage, chinese (pe-tsai), raw' },
  { id: 'pak_choi', name: 'Pak Choi', kategorie: gemuese, usda: 'Cabbage, chinese (pak-choi), raw' },
  { id: 'kohlrabi', name: 'Kohlrabi', kategorie: gemuese, usda: 'Kohlrabi, raw', stueckG: 250 },
  { id: 'zwiebel', name: 'Zwiebel', kategorie: gemuese, usda: 'Onions, raw', stueckG: 100 },
  { id: 'knoblauch', name: 'Knoblauch', kategorie: gemuese, usda: 'Garlic, raw', stueckG: 4 },
  { id: 'lauch', name: 'Lauch/Porree', kategorie: gemuese, usda: 'Leeks, (bulb and lower leaf-portion), raw' },
  { id: 'champignons', name: 'Champignons', kategorie: gemuese, usda: 'Mushrooms, white, raw' },
  { id: 'erbsen', name: 'Erbsen (TK)', kategorie: gemuese, usda: 'Peas, green, frozen, unprepared' },
  { id: 'gruene_bohnen', name: 'Grüne Bohnen', kategorie: gemuese, usda: 'Beans, snap, green, raw' },
  { id: 'mais', name: 'Mais (Dose, abgetropft)', kategorie: gemuese, usda: 'Corn, sweet, yellow, canned, whole kernel, drained solids' },
  { id: 'edamame', name: 'Edamame (TK)', kategorie: gemuese, usda: 'Edamame, frozen, unprepared' },
  { id: 'gemuese_mix_tk', name: 'Gemüsemischung (TK)', kategorie: gemuese, usda: 'Vegetables, mixed, frozen, unprepared' },
  { id: 'kartoffel', name: 'Kartoffel', kategorie: gemuese, usda: 'Potatoes, flesh and skin, raw', stueckG: 150 },
  { id: 'suesskartoffel', name: 'Süßkartoffel', kategorie: gemuese, usda: 'Sweet potato, raw, unprepared', stueckG: 250 },
  { id: 'rote_bete', name: 'Rote Bete', kategorie: gemuese, usda: 'Beets, raw' },
  { id: 'staudensellerie', name: 'Staudensellerie', kategorie: gemuese, usda: 'Celery, raw' },
  { id: 'knollensellerie', name: 'Knollensellerie', kategorie: gemuese, usda: 'Celeriac, raw' },
  { id: 'fenchel', name: 'Fenchel', kategorie: gemuese, usda: 'Fennel, bulb, raw' },
  { id: 'spargel', name: 'Spargel (grün)', kategorie: gemuese, usda: 'Asparagus, raw' },
  { id: 'kuerbis', name: 'Kürbis (Hokkaido)', kategorie: gemuese, usda: 'Squash, winter, all varieties, raw' },
  { id: 'pastinake', name: 'Pastinake', kategorie: gemuese, usda: 'Parsnips, raw' },
  { id: 'mangold', name: 'Mangold', kategorie: gemuese, usda: 'Chard, swiss, raw' },
  { id: 'radieschen', name: 'Radieschen', kategorie: gemuese, usda: 'Radishes, raw' },
  { id: 'rucola', name: 'Rucola', kategorie: gemuese, usda: 'Arugula, raw' },
  { id: 'eisbergsalat', name: 'Eisbergsalat', kategorie: gemuese, usda: 'Lettuce, iceberg (includes crisphead types), raw' },
  { id: 'romanasalat', name: 'Romanasalat', kategorie: gemuese, usda: 'Lettuce, cos or romaine, raw' },
  { id: 'avocado', name: 'Avocado', kategorie: gemuese, usda: 'Avocados, raw, all commercial varieties', stueckG: 150 },
  { id: 'tomaten_passiert', name: 'Passierte Tomaten', kategorie: gemuese, usda: 'Tomato products, canned, puree, without salt added' },
  { id: 'tomaten_stueckig', name: 'Tomaten, stückig (Dose)', kategorie: gemuese, usda: 'Tomatoes, red, ripe, canned, packed in tomato juice' },
  { id: 'tomatenmark', name: 'Tomatenmark', kategorie: gemuese, usda: 'Tomato products, canned, paste, without salt added' },
  { id: 'sauerkraut', name: 'Sauerkraut', kategorie: gemuese, usda: 'Sauerkraut, canned, solids and liquids' },
  { id: 'ingwer', name: 'Ingwer', kategorie: gemuese, usda: 'Ginger root, raw' },
  { id: 'petersilie', name: 'Petersilie', kategorie: gemuese, usda: 'Parsley, fresh' },

  // Getreide und Brot
  { id: 'haferflocken', name: 'Haferflocken', kategorie: getreide, usda: 'Cereals, oats, regular and quick, not fortified, dry' },
  { id: 'reis', name: 'Reis, weiß (roh)', kategorie: getreide, usda: 'Rice, white, long-grain, regular, raw, unenriched' },
  { id: 'reis_vollkorn', name: 'Vollkornreis (roh)', kategorie: getreide, usda: 'Rice, brown, long-grain, raw' },
  { id: 'nudeln', name: 'Nudeln (roh)', kategorie: getreide, usda: 'Pasta, dry, unenriched' },
  { id: 'vollkornnudeln', name: 'Vollkornnudeln (roh)', kategorie: getreide, usda: 'Pasta, whole-wheat, dry' },
  { id: 'quinoa', name: 'Quinoa (roh)', kategorie: getreide, usda: 'Quinoa, uncooked' },
  { id: 'couscous', name: 'Couscous (roh)', kategorie: getreide, usda: 'Couscous, dry' },
  { id: 'bulgur', name: 'Bulgur (roh)', kategorie: getreide, usda: 'Bulgur, dry' },
  { id: 'hirse', name: 'Hirse (roh)', kategorie: getreide, usda: 'Millet, raw' },
  { id: 'buchweizen', name: 'Buchweizen (roh)', kategorie: getreide, usda: 'Buckwheat' },
  { id: 'weizenmehl', name: 'Weizenmehl Type 405', kategorie: getreide, usda: 'Wheat flour, white, all-purpose, unenriched' },
  { id: 'vollkornmehl', name: 'Weizenvollkornmehl', kategorie: getreide, usda: 'Wheat flour, whole-grain' },
  { id: 'dinkel', name: 'Dinkel (Korn/Mehl)', kategorie: getreide, usda: 'Spelt, uncooked' },
  { id: 'polenta', name: 'Polenta/Maisgrieß', kategorie: getreide, usda: 'Cornmeal, whole-grain, yellow' },
  { id: 'vollkornbrot', name: 'Vollkornbrot', kategorie: getreide, usda: 'Bread, whole-wheat, commercially prepared', stueckG: 50 },
  { id: 'roggenbrot', name: 'Roggenbrot', kategorie: getreide, usda: 'Bread, rye', stueckG: 50 },
  { id: 'toast', name: 'Toastbrot', kategorie: getreide, usda: 'Bread, white, commercially prepared (includes soft bread crumbs)', stueckG: 25 },
  { id: 'knaeckebrot', name: 'Knäckebrot (Roggen)', kategorie: getreide, usda: 'Crackers, rye, wafers, plain', stueckG: 10 },
  { id: 'reiswaffeln', name: 'Reiswaffeln', kategorie: getreide, usda: 'Snacks, rice cakes, brown rice, multigrain', stueckG: 8 },
  { id: 'tortilla', name: 'Weizentortilla', kategorie: getreide, usda: 'Tortillas, ready-to-bake or -fry, flour, refrigerated', stueckG: 60 },
  { id: 'cornflakes', name: 'Cornflakes', kategorie: getreide, usda: 'Cereals ready-to-eat, RALSTON Corn Flakes' },

  // Hülsenfrüchte und Soja
  { id: 'linsen', name: 'Linsen, braun (roh)', kategorie: huelsen, usda: 'Lentils, raw' },
  { id: 'linsen_rot', name: 'Linsen, rot (roh)', kategorie: huelsen, usda: 'Lentils, pink or red, raw' },
  { id: 'kichererbsen', name: 'Kichererbsen (roh)', kategorie: huelsen, usda: 'Chickpeas (garbanzo beans, bengal gram), mature seeds, raw' },
  { id: 'kichererbsen_dose', name: 'Kichererbsen (Dose)', kategorie: huelsen, usda: 'Chickpeas (garbanzo beans, bengal gram), mature seeds, canned, drained, rinsed in tap water' },
  { id: 'kidneybohnen', name: 'Kidneybohnen (roh)', kategorie: huelsen, usda: 'Beans, kidney, red, mature seeds, raw' },
  { id: 'kidneybohnen_dose', name: 'Kidneybohnen (Dose)', kategorie: huelsen, usda: 'Beans, kidney, red, mature seeds, canned, drained solids' },
  { id: 'schwarze_bohnen_dose', name: 'Schwarze Bohnen (Dose)', kategorie: huelsen, usda: 'Beans, black, mature seeds, canned, low sodium' },
  { id: 'weisse_bohnen_dose', name: 'Weiße Bohnen (Dose)', kategorie: huelsen, usda: 'Beans, white, mature seeds, canned' },
  { id: 'tofu', name: 'Tofu natur', kategorie: huelsen, usda: 'Tofu, raw, firm, prepared with calcium sulfate' },
  { id: 'hummus', name: 'Hummus', kategorie: huelsen, usda: 'Hummus, commercial' },
  { id: 'erdnussbutter', name: 'Erdnussmus', kategorie: huelsen, usda: 'Peanut butter, smooth style, without salt' },

  // Milchprodukte und Eier (Milch ohne US-Vitaminanreicherung)
  { id: 'milch_vollmilch', name: 'Vollmilch 3,5 %', kategorie: milch, usda: 'Milk, whole, 3.25% milkfat, without added vitamin A and vitamin D' },
  { id: 'milch_fettarm', name: 'Fettarme Milch 1,5 %', kategorie: milch, usda: 'Milk, reduced fat, fluid, 2% milkfat, without added vitamin A and vitamin D' },
  { id: 'joghurt', name: 'Naturjoghurt 1,5 %', kategorie: milch, usda: 'Yogurt, plain, low fat' },
  { id: 'griechischer_joghurt', name: 'Griechischer Joghurt', kategorie: milch, usda: 'Yogurt, Greek, plain, whole milk' },
  { id: 'huettenkaese', name: 'Hüttenkäse/Körniger Frischkäse', kategorie: milch, usda: 'Cheese, cottage, lowfat, 2% milkfat' },
  { id: 'mozzarella', name: 'Mozzarella light', kategorie: milch, usda: 'Cheese, mozzarella, part skim milk' },
  { id: 'gouda', name: 'Gouda', kategorie: milch, usda: 'Cheese, gouda', stueckG: 20 },
  { id: 'parmesan', name: 'Parmesan/Grana Padano', kategorie: milch, usda: 'Cheese, parmesan, hard' },
  { id: 'feta', name: 'Feta', kategorie: milch, usda: 'Cheese, feta' },
  { id: 'frischkaese', name: 'Frischkäse', kategorie: milch, usda: 'Cheese, cream' },
  { id: 'butter', name: 'Butter', kategorie: milch, usda: 'Butter, without salt' },
  { id: 'ei', name: 'Ei', kategorie: milch, usda: 'Egg, whole, raw, fresh', stueckG: 55 },
  { id: 'eiklar', name: 'Eiklar', kategorie: milch, usda: 'Egg, white, raw, fresh', stueckG: 33 },
  { id: 'skyr', name: 'Skyr natur', kategorie: milch, eigen: { kcal: 63, protein: 11, kh: 4, fett: 0.2, zucker: 4 } },
  { id: 'magerquark', name: 'Magerquark', kategorie: milch, eigen: { kcal: 67, protein: 12, kh: 4, fett: 0.2, zucker: 4 } },
  { id: 'harzer', name: 'Harzer Käse', kategorie: milch, eigen: { kcal: 120, protein: 27, kh: 0, fett: 0.5 } },

  // Fleisch und Fisch (roh)
  { id: 'haehnchenbrust', name: 'Hähnchenbrust (roh)', kategorie: fleisch, usda: 'Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw' },
  { id: 'putenbrust', name: 'Putenbrust (roh)', kategorie: fleisch, usda: 'Turkey, retail parts, breast, meat only, raw' },
  { id: 'rinderhack', name: 'Rinderhack 15 % Fett (roh)', kategorie: fleisch, usda: 'Beef, ground, 85% lean meat / 15% fat, raw' },
  { id: 'rinderhack_mager', name: 'Rinderhack 5 % Fett (roh)', kategorie: fleisch, usda: 'Beef, ground, 95% lean meat / 5% fat, raw' },
  { id: 'schweinefilet', name: 'Schweinefilet (roh)', kategorie: fleisch, usda: 'Pork, fresh, loin, tenderloin, separable lean only, raw' },
  { id: 'kochschinken', name: 'Kochschinken', kategorie: fleisch, eigen: { kcal: 105, protein: 19, kh: 1, fett: 3 } },
  { id: 'lachs', name: 'Lachs (roh)', kategorie: fleisch, usda: 'Fish, salmon, Atlantic, farmed, raw' },
  { id: 'thunfisch_dose', name: 'Thunfisch im eigenen Saft', kategorie: fleisch, usda: 'Fish, tuna, light, canned in water, without salt, drained solids' },
  { id: 'kabeljau', name: 'Kabeljau (roh)', kategorie: fleisch, usda: 'Fish, cod, Atlantic, raw' },
  { id: 'seelachs', name: 'Alaska-Seelachs (roh)', kategorie: fleisch, usda: 'Fish, pollock, Alaska, raw' },
  { id: 'garnelen', name: 'Garnelen (roh)', kategorie: fleisch, usda: 'Crustaceans, shrimp, raw' },
  { id: 'makrele', name: 'Makrele (roh)', kategorie: fleisch, usda: 'Fish, mackerel, Atlantic, raw' },
  { id: 'hering', name: 'Hering (roh)', kategorie: fleisch, usda: 'Fish, herring, Atlantic, raw' },
  { id: 'sardinen', name: 'Sardinen in Öl (abgetropft)', kategorie: fleisch, usda: 'Fish, sardine, Atlantic, canned in oil, drained solids with bone' },

  // Nüsse und Samen
  { id: 'mandeln', name: 'Mandeln', kategorie: nuesse, usda: 'Nuts, almonds' },
  { id: 'walnuesse', name: 'Walnüsse', kategorie: nuesse, usda: 'Nuts, walnuts, english' },
  { id: 'haselnuesse', name: 'Haselnüsse', kategorie: nuesse, usda: 'Nuts, hazelnuts or filberts' },
  { id: 'cashews', name: 'Cashewkerne', kategorie: nuesse, usda: 'Nuts, cashew nuts, raw' },
  { id: 'paranuesse', name: 'Paranüsse', kategorie: nuesse, usda: 'Nuts, brazilnuts, dried, unblanched', stueckG: 5 },
  { id: 'erdnuesse', name: 'Erdnüsse', kategorie: nuesse, usda: 'Peanuts, all types, raw' },
  { id: 'chiasamen', name: 'Chiasamen', kategorie: nuesse, usda: 'Seeds, chia seeds, dried' },
  { id: 'leinsamen', name: 'Leinsamen', kategorie: nuesse, usda: 'Seeds, flaxseed' },
  { id: 'kuerbiskerne', name: 'Kürbiskerne', kategorie: nuesse, usda: 'Seeds, pumpkin and squash seed kernels, dried' },
  { id: 'sonnenblumenkerne', name: 'Sonnenblumenkerne', kategorie: nuesse, usda: 'Seeds, sunflower seed kernels, dried' },
  { id: 'sesam', name: 'Sesam', kategorie: nuesse, usda: 'Seeds, sesame seeds, whole, dried' },
  { id: 'hanfsamen', name: 'Hanfsamen, geschält', kategorie: nuesse, usda: 'Seeds, hemp seed, hulled' },

  // Öle und Fette
  { id: 'olivenoel', name: 'Olivenöl', kategorie: fette, usda: 'Oil, olive, salad or cooking' },
  { id: 'rapsoel', name: 'Rapsöl', kategorie: fette, usda: 'Oil, canola' },
  { id: 'leinoel', name: 'Leinöl', kategorie: fette, usda: 'Oil, flaxseed, cold pressed' },
  { id: 'kokosoel', name: 'Kokosöl', kategorie: fette, usda: 'Oil, coconut' },
  { id: 'schwarzkuemmeloel', name: 'Schwarzkümmelöl, kaltgepresst', kategorie: fette, eigen: { kcal: 884, protein: 0, kh: 0, fett: 100, gesFett: 15 } },

  // Süßes
  { id: 'honig', name: 'Honig', kategorie: suess, usda: 'Honey' },
  { id: 'manuka_honig', name: 'Manuka-Honig', kategorie: suess, usda: 'Honey' },
  { id: 'ahornsirup', name: 'Ahornsirup', kategorie: suess, usda: 'Syrups, maple' },
  { id: 'zucker', name: 'Zucker', kategorie: suess, usda: 'Sugars, granulated' },
  { id: 'marmelade', name: 'Konfitüre', kategorie: suess, usda: 'Jams and preserves' },
  { id: 'zartbitterschokolade', name: 'Zartbitterschokolade 70–85 %', kategorie: suess, usda: 'Chocolate, dark, 70-85% cacao solids' },
  // USDA-kcal für Kakao (228) passt nicht zu deutschen Packungen (~350) → aus Makros berechnen
  { id: 'kakao', name: 'Kakaopulver, ungesüßt', kategorie: suess, usda: 'Cocoa, dry powder, unsweetened', kcalAusMakros: true },

  // Getränke
  { id: 'orangensaft', name: 'Orangensaft', kategorie: getraenke, usda: 'Orange juice, raw' },
  { id: 'apfelsaft', name: 'Apfelsaft', kategorie: getraenke, usda: 'Apple juice, canned or bottled, unsweetened, without added ascorbic acid' },
  { id: 'rote_bete_saft', name: 'Rote-Bete-Saft', kategorie: getraenke, eigen: { kcal: 38, protein: 1, kh: 8.5, zucker: 8, fett: 0 } },
  { id: 'haferdrink', name: 'Haferdrink', kategorie: getraenke, eigen: { kcal: 46, protein: 0.5, kh: 6.7, fett: 1.5 } },
  { id: 'kaffee', name: 'Kaffee', kategorie: getraenke, usda: 'Beverages, coffee, brewed, prepared with tap water' },
  { id: 'gruener_tee', name: 'Grüner Tee', kategorie: getraenke, usda: 'Beverages, tea, green, brewed, regular' },

  // Sonstiges und Gewürze
  { id: 'whey', name: 'Whey-Protein (Konzentrat)', kategorie: sonstiges, eigen: { kcal: 380, protein: 75, kh: 8, fett: 6 } },
  { id: 'naehrhefe', name: 'Nährhefeflocken', kategorie: sonstiges, eigen: { kcal: 375, protein: 50, kh: 17, fett: 5, ballaststoffe: 21 } },
  { id: 'flohsamenschalen', name: 'Flohsamenschalen', kategorie: sonstiges, eigen: { kcal: 190, protein: 2, kh: 2, fett: 0.6, ballaststoffe: 85 } },
  { id: 'kreatin', name: 'Kreatin-Monohydrat', kategorie: sonstiges, eigen: { kcal: 0, protein: 0, kh: 0, fett: 0 } },
  { id: 'sojasauce', name: 'Sojasauce', kategorie: sonstiges, usda: 'Soy sauce made from soy and wheat (shoyu)' },
  { id: 'senf', name: 'Senf', kategorie: sonstiges, usda: 'Mustard, prepared, yellow' },
  { id: 'ketchup', name: 'Ketchup', kategorie: sonstiges, usda: 'Catsup' },
  { id: 'salz', name: 'Salz', kategorie: sonstiges, usda: 'Salt, table' },
  { id: 'zimt', name: 'Zimt', kategorie: sonstiges, usda: 'Spices, cinnamon, ground' },
  { id: 'kurkuma', name: 'Kurkuma', kategorie: sonstiges, usda: 'Spices, turmeric, ground' },
];
